import time
import pytest

from pages.dashboard import Test_Login
from pages.login_page import LoginPage
from pages.cloud_connect import Clod_Connect


@pytest.mark.usefixtures("setup_and_teardown")
class TestCloudConnect:
    def test_cloud_connect_manage_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        message = "Cloud Connect"
        assert cloud.verify_cloud_connect_text().__eq__(message)
        cloud.current_url()
        # self.driver.save_screenshot()
        self.driver.quit()

    def test_cloud_connect_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        message = "Overview"
        assert cloud.cloud_connect_verify_text().__eq__(message)
        cloud.current_url()
        # self.driver.save_screenshot()
        self.driver.quit()

    def test_cloud_connect_overview_page_link_status(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.overview_button()
        time.sleep(1)
        cloud.link_status_text()
        cloud.link_status_data()
        cloud.current_url()
        # self.driver.save_screenshot()
        self.driver.quit()

    def test_cloud_connect_overview_page_device_status_verify_routers_list(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.overview_button()
        time.sleep(1)
        cloud.device_status_text()
        time.sleep(1)
        cloud.device_status_arrow_routers_button()
        time.sleep(1)
        cloud.routers_lengtn_list()
        cloud.current_url()
        # self.driver.save_screenshot()
        self.driver.quit()

    def test_cloud_connect_overview_page_device_status(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.overview_button()
        time.sleep(1)
        cloud.device_status_text()
        time.sleep(1)
        cloud.device_status_arrow_routers_button()
        time.sleep(1)
        cloud.routers_list()
        time.sleep(1)
        cloud.device_status_data()
        # cloud.current_url()
        # self.driver.save_screenshot()
        self.driver.quit()


    def test_cloud_connect_overview_page_exchange(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.overview_button()
        time.sleep(1)
        cloud.exchange_button()
        time.sleep(1)
        cloud.exchange_list_data_text()
        # self.driver.save_screenshot()
        self.driver.quit()


    def test_cloud_connect_overview_page_public(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.overview_button()
        time.sleep(1)
        cloud.public_button()
        time.sleep(1)
        cloud.public_button_data()
        # self.driver.save_screenshot()
        self.driver.quit()

    def test_cloud_connect_overview_page_cc_dci(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.overview_button()
        time.sleep(1)
        cloud.cc_dci_button()
        time.sleep(1)
        cloud.cc_dci_button_data()
        # self.driver.save_screenshot()
        self.driver.quit()

    def test_cloud_connect_overview_page_link_insight_message(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.overview_button()
        time.sleep(1)
        cloud.message_button()
        time.sleep(1)
        cloud.message_links_arrow_button()
        time.sleep(1)
        cloud.message_links_length_list()
        cloud.message_links_list()
        self.driver.implicitly_wait(10)
        cloud.message_commodity_text()
        cloud.message_graph()
        # self.driver.save_screenshot()
        self.driver.quit()


    def test_cloud_connect_overview_page_link_insight_app_latency(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.overview_button()
        time.sleep(1)
        cloud.app_latency_button()
        time.sleep(1)
        cloud.app_latency_links_arrow_button()
        time.sleep(1)
        cloud.app_latency_links_length_list()
        cloud.app_latency_links_list()
        self.driver.implicitly_wait(10)
        cloud.app_latency_commodity_text()
        # cloud.message_graph()
        # self.driver.save_screenshot()
        self.driver.quit()


    def test_cloud_connect_overview_page_link_insight_app_event_logs(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.overview_button()
        time.sleep(1)
        cloud.app_event_logs_button()
        time.sleep(1)
        cloud.app_event_logs_data()
         # self.driver.save_screenshot()
        self.driver.quit()

    def test_cloud_connect_overview_page_link_insight_HA_logs(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.overview_button()
        time.sleep(1)
        cloud.ha_logs_button()
        time.sleep(1)
        cloud.ha_logs_protocol_drop_down()
        time.sleep(1)
        cloud.ha_logs_protocol_drop_down_list_items()
        time.sleep(1)
        cloud.ha_logs_protocol_drop_down_list_data()
         # self.driver.save_screenshot()
        self.driver.quit()

    def test_cloud_connect_configuration_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.configuration_button()
        time.sleep(2)
        message = "Router Configuration"
        cloud.verify_configuration_page_text().__eq__(message)
        self.driver.quit()

    def test_cloud_connect_configuration_page_table(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.configuration_button()
        cloud.configuration_table_data()
        self.driver.quit()

    def test_cloud_connect_configuration_page_table_state(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.configuration_button()
        time.sleep(1)
        cloud.configuration_state_button()
        self.driver.quit()

    def test_cloud_connect_configuration_page_table_action_button(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.configuration_button()
        time.sleep(1)
        cloud.configuration_table_action_button()
        cloud.configuration_table_action_button_list_items()
        self.driver.quit()

    def test_cloud_connect_configuration_page_add_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.configuration_button()
        time.sleep(1)
        cloud.configuration_add_button()
        time.sleep(1)
        message = "Cloud Connect Configuration"
        assert cloud.verify_configuration_add_page_text().__eq__(message)
        self.driver.quit()

    def test_cloud_connect_configuration_page_csv(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.configuration_button()
        time.sleep(1)
        cloud.configuration_csv_button()
        time.sleep(2)
        self.driver.save_screenshot("cloud_connect_verify_csv.png")
        self.driver.quit()

    def test_cloud_connect_usage_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.usage_button()
        time.sleep(1)
        massage = "Router Name"
        assert cloud.verify_usage_page().__eq__(massage)
        self.driver.quit()

    def test_cloud_connect_usage_page_verify_router_drop_down(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.usage_button()
        time.sleep(1)
        cloud.routers_dropdown_button()
        time.sleep(1)
        cloud.routers_drop_down_list_items()
        time.sleep(1)
        message = "Bandwidth"
        assert cloud.verify_page_for_routers().__eq__(message)
        self.driver.quit()

    def test_cloud_connect_usage_page_router_drop_down_and_interval_drop_down(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.usage_button()
        time.sleep(1)
        cloud.routers_dropdown_button()
        time.sleep(1)
        cloud.routers_drop_down_list_items()
        time.sleep(1)
        cloud.interval_dropdown_button()
        time.sleep(1)
        cloud.interval_drop_down_list_items()
        time.sleep(1)
        message = "Bandwidth"
        assert cloud.verify_page_for_routers().__eq__(message)
        cloud.usage_graph()
        self.driver.quit()


    def test_cloud_connect_usage_page_table_data(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.usage_button()
        time.sleep(1)
        cloud.routers_dropdown_button()
        time.sleep(1)
        cloud.routers_drop_down_list_items()
        time.sleep(1)
        cloud.interval_dropdown_button()
        time.sleep(1)
        cloud.interval_drop_down_list_items()
        time.sleep(1)
        cloud.rows_per_page_down_button()
        time.sleep(1)
        cloud.usage_table_data()
        self.driver.quit()

    def test_cloud_connect_usage_page_table_data_for_topapps_airtel(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.usage_button()
        time.sleep(1)
        cloud.routers_dropdown_button()
        time.sleep(1)
        cloud.routers_drop_down_list_items()
        time.sleep(1)
        cloud.interval_dropdown_button()
        time.sleep(1)
        cloud.interval_drop_down_list_items()
        time.sleep(1)
        cloud.rows_per_page_down_button()
        time.sleep(1)
        cloud.usage_table_data_for_top_apps_airtel()
        self.driver.quit()

    def test_cloud_connect_usage_page_each_row_verify_table_data(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("trade@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        cloud = Clod_Connect(self.driver)
        cloud.manage_page()
        time.sleep(1)
        cloud.cloud_connect_button()
        time.sleep(2)
        cloud.usage_button()
        time.sleep(1)
        cloud.routers_dropdown_button()
        time.sleep(1)
        cloud.routers_drop_down_list_items()
        time.sleep(1)
        cloud.interval_dropdown_button()
        time.sleep(1)
        cloud.interval_drop_down_list_items()
        time.sleep(1)
        cloud.rows_per_page_down_button()
        time.sleep(1)
        cloud.total_table_data_for_each_single_row()
        self.driver.quit()