
import time
import pytest

from Pages.Dashboardpage import Test_Login
from Pages.loginpage import LoginPage
from Pages.ip_tracking import Iptracking


@pytest.mark.usefixtures("setup_and_teardown")
class TestIpTracking:
    def test_verify_report_login_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        ip = Iptracking(self.driver)
        message = "Reports"
        assert ip.verify_report_button().__eq__(message)
        self.driver.quit()


    def test_report_iptracking_login_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        ip = Iptracking(self.driver)
        ip.iptracking_page()
        time.sleep(4)
        message = "External IP Communication"
        assert ip.verify_ip_tracking_page().__eq__(message)
        self.driver.quit()

    def test_select_date_and_time(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        ip = Iptracking(self.driver)
        ip.iptracking_page()
        time.sleep(4)
        ip.from_date()
        time.sleep(4)
        ip.to_date()
        time.sleep(4)
        ip.public_ip_dropdown_button()
        time.sleep(3)
        ip.public_ip_list()
        time.sleep(3)
        ip.submit_button()

    def test_ip_tracking_display_data(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        ip = Iptracking(self.driver)
        ip.iptracking_page()
        time.sleep(4)
        ip.from_date()
        time.sleep(4)
        ip.to_date()
        time.sleep(4)
        ip.public_ip_dropdown_button()
        time.sleep(3)
        ip.public_ip_list()
        time.sleep(3)
        ip.submit_button()
        time.sleep(4)
        ip.ip_tracking_table_data()
        self.driver.quit()


    def test_ip_tracking_table_received_data(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        ip = Iptracking(self.driver)
        ip.iptracking_page()
        time.sleep(4)
        ip.from_date()
        time.sleep(4)
        ip.to_date()
        time.sleep(4)
        ip.public_ip_dropdown_button()
        time.sleep(3)
        ip.public_ip_list()
        time.sleep(3)
        ip.submit_button()
        time.sleep(4)
        ip.ip_tracking_table_data()
        time.sleep(3)
        ip.ip_tracking_table_received_data()
        self.driver.quit()


    def test_ip_tracking_table_transmitted_data(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        ip = Iptracking(self.driver)
        ip.iptracking_page()
        time.sleep(4)
        ip.from_date()
        time.sleep(4)
        ip.to_date()
        time.sleep(4)
        ip.public_ip_dropdown_button()
        time.sleep(3)
        ip.public_ip_list()
        time.sleep(3)
        ip.submit_button()
        time.sleep(4)
        ip.ip_tracking_table_data()
        time.sleep(3)
        ip.ip_tracking_table_transmitted_data()
        self.driver.quit()

    def test_ip_tracking_table_total_data(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        ip = Iptracking(self.driver)
        ip.iptracking_page()
        time.sleep(4)
        ip.from_date()
        time.sleep(4)
        ip.to_date()
        time.sleep(4)
        ip.public_ip_dropdown_button()
        time.sleep(3)
        ip.public_ip_list()
        time.sleep(3)
        ip.submit_button()
        time.sleep(4)
        ip.ip_tracking_table_data()
        time.sleep(3)
        ip.ip_tracking_table_total_data()
        self.driver.quit()

    def test_ip_tracking_table_verify(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(3)
        ip = Iptracking(self.driver)
        ip.iptracking_page()
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(4)
        ip.from_date()
        time.sleep(4)
        ip.to_date()
        time.sleep(4)
        ip.public_ip_dropdown_button()
        time.sleep(3)
        ip.public_ip_list()
        time.sleep(3)
        ip.submit_button()
        time.sleep(4)
        # ip.ip_tracking_table_data()
        # time.sleep(3)
        ip.verify_data()
        self.driver.quit()

