import time
import pytest
from Pages.loginpage import LoginPage
from Pages.instance import InstancePage

@pytest.mark.usefixtures("setup_and_teardown")
class TestInstance:
     def test_login_page_with_credentials(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          self.driver.quit()

     def test_manage_instance_page(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          message = "Instances"
          assert instance.verify_instances_text().__eq__(message)
          time.sleep(3)
          self.driver.quit()
     def test_manage_instance_page_table(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(3)
          instance.instance_total_rows()
          time.sleep(3)
          instance.instance_total_columns()
          time.sleep(3)
          instance.instance_table_data()
          self.driver.quit()

     def test_manage_instance_table_click_on_instance(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(5)
          instance.instance_page()
          time.sleep(4)
          instance.table_instance_button()
          time.sleep(5)
          instance.table_instance_data()

     def test_manage_instance_table_click_on_notification(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(5)
          instance.instance_page()
          time.sleep(4)
          instance.table_instance_notification_button()
          time.sleep(4)
          instance.table_instance_notification_data()
          self.driver.quit()


     def test_instance_performance(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(3)
          instance.table_instance_action_performance()
          time.sleep(3)
          instance.action_performance()
          time.sleep(3)
          instance.performance_instance_button()

     def test_instance_performance_select(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(3)
          instance.table_instance_action_performance()
          time.sleep(3)
          instance.action_performance()
          time.sleep(5)
          instance.performance_instance_button()
          time.sleep(5)
          instance.select_instance_check_box()
          time.sleep(5)
          instance.service_button()
          time.sleep(5)
          instance.service_dropdown_list()
          time.sleep(5)
          instance.intervel_dropdown()
          time.sleep(10)
          instance.dropdown_listitems()
          time.sleep(5)
          instance.submit_button()
          time.sleep(3)

     def test_instance_warning(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(3)
          instance.instance_warnings()
          time.sleep(3)
          instance.warning_table_data()

     def test_instance_criticals(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(5)
          instance.instance_criticals()
          time.sleep(3)
          instance.critical_table_data()
          time.sleep(3)

     def test_instance_table_ok(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(5)
          instance.instance_table_ok_button()

     def test_instance_table_warn(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(5)
          instance.instance_table_warn_button()

     def test_instance_table_crit(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(5)
          instance.instance_table_crit_button()


     def test_instance_table_verify_total(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(5)
          instance.verify_total_service()


     def test_instance_table_warnings(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(3)
          instance.instance_warnings()
          time.sleep(3)
          instance.instance_no_of_warnings()

     def test_instance_table_criticals(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          time.sleep(5)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(3)
          instance.instance_criticals()
          time.sleep(3)
          instance.instance_no_of_criticals()




