import time
import pytest

from pages.dashboard import Test_Login
from pages.login_page import LoginPage
from pages.instance import InstancePage
from pages.firewall_page import FirewallPage


@pytest.mark.usefixtures("setup_and_teardown")
class TestFirewall:
    def test_verify_firewall_policy_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        firewall = FirewallPage(self.driver)
        firewall.manage_page()
        message = "Firewall"
        assert firewall.verify_firewall_page().__eq__(message)
        firewall.current_url()
        self.driver.save_screenshot("firewall.png")
        self.driver.quit()

    def test_firewall_policy_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(1)
        message = "Firewall Assessment last 30 days"
        assert firewall.verify_firewall_page_text().__eq__(message)
        firewall.current_url()
        self.driver.save_screenshot("verify_firewall.png")
        self.driver.quit()

    def test_firewall_policy_overview_tabel_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(1)
        firewall.overview_button()
        time.sleep(1)
        firewall.firewall_policy_button()
        time.sleep(1)
        firewall.firewall_policy_table_data()
        self.driver.save_screenshot("firewall_table.png")
        self.driver.quit()

    def test_firewall_policy_overview_activity_tabel_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(1)
        firewall.overview_button()
        time.sleep(1)
        firewall.overview_activity_table()
        time.sleep(1)
        firewall.firewall_policy_overview_activity_table_data()
        time.sleep(3)
        self.driver.save_screenshot("firewall_policy_overview_activity_tabel.png")
        self.driver.quit()


    def test_firewall_incoming_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(1)
        firewall.incoming_button()
        time.sleep(2)
        message = "WAN"
        assert firewall.verify_incoming_page_text().__eq__(message)
        self.driver.save_screenshot("firewall_incoming_page.png")
        self.driver.quit()


    def test_firewall_incoming_wan_tabel_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(1)
        firewall.incoming_button()
        time.sleep(1)
        firewall.incoming_select_instance_all_button()
        time.sleep(1)
        firewall.incoming_wan_button()
        time.sleep(1)
        firewall.firewall_incoming_wan_table_data()
        self.driver.save_screenshot("firewall_firewall_incoming_wan_tabel.png")
        self.driver.quit()

    def test_firewall_incoming_captive_tabel_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(1)
        firewall.incoming_button()
        time.sleep(1)
        firewall.incoming_select_instance_all_button()
        time.sleep(1)
        firewall.incoming_captive_button()
        time.sleep(1)
        firewall.firewall_incoming_captive_table_row_data()
        time.sleep(1)
        firewall.firewall_incoming_captive_table_data()
        self.driver.save_screenshot("firewall_incoming_captive_tabel.png")
        self.driver.quit()


    def test_firewall_incoming_others_tabel_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(1)
        firewall.incoming_button()
        time.sleep(1)
        firewall.incoming_select_instance_all_button()
        time.sleep(1)
        firewall.incoming_others_table_button()
        time.sleep(1)
        firewall.firewall_incoming_others_table_row_data()
        time.sleep(1)
        firewall.firewall_incoming_others_table_data()
        self.driver.save_screenshot("firewall_incoming_others_tabel.png")
        self.driver.quit()


    def test_firewall_incoming_wan_tabel_for_single_instance(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(3)
        firewall.incoming_button()
        time.sleep(1)
        firewall.incoming_select_one_instance_button()
        time.sleep(1)
        firewall.incoming_wan_button()
        time.sleep(1)
        firewall.firewall_incoming_wan_table_data()
        time.sleep(2)
        firewall.incoming_captive_button()
        time.sleep(1)
        firewall.firewall_incoming_captive_table_row_data()
        time.sleep(1)
        firewall.firewall_incoming_captive_table_data()
        time.sleep(2)
        firewall.incoming_others_table_button()
        time.sleep(1)
        firewall.firewall_incoming_others_table_row_data()
        time.sleep(1)
        firewall.firewall_incoming_others_table_data()
        self.driver.save_screenshot("firewall_incoming_wan_tabel_for_single_instance.png")
        self.driver.quit()



    def test_firewall_outgoing_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(1)
        firewall.outgoing_button()
        time.sleep(2)
        message = "Captive"
        assert firewall.verify_outgoing_page_text().__eq__(message)
        self.driver.save_screenshot("firewall_outgoing_page.png")
        self.driver.quit()

    def test_firewall_outgoing_wan_table_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(1)
        firewall.outgoing_button()
        time.sleep(1)
        firewall.incoming_select_instance_all_button()
        time.sleep(1)
        firewall.outgoing_wan_button()
        time.sleep(1)
        firewall.firewall_outgoing_wan_table_data()
        self.driver.save_screenshot("firewall_outgoing_wan_table_page.png")
        self.driver.quit()

    def test_firewall_outgoing_captive_table_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(3)
        firewall.outgoing_button()
        time.sleep(1)
        firewall.incoming_select_instance_all_button()
        time.sleep(3)
        firewall.outgoing_captive_button()
        time.sleep(3)
        firewall.firewall_outgoing_captive_table_data()
        self.driver.save_screenshot("firewall_outgoing_captive_table_page.png")
        self.driver.quit()

    def test_firewall_outgoing_lan_others_table_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(3)
        firewall.outgoing_button()
        time.sleep(1)
        firewall.incoming_select_instance_all_button()
        time.sleep(3)
        firewall.outgoing_lan_others_button()
        time.sleep(3)
        firewall.firewall_outgoing_lan_others_table_data()
        self.driver.save_screenshot("firewall_outgoing_lan_others_table_page.png")
        self.driver.quit()

    def test_incoming_page_total_instance(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        firewall = FirewallPage(self.driver)
        firewall.manage_firewall_page()
        time.sleep(3)
        firewall.incoming_button()
        time.sleep(3)
        firewall.dropdown_arrow_button()
        time.sleep(3)
        firewall.all_button()
        self.driver.save_screenshot("firewall_incoming_page_total_instance.png")







