import os
import time
import re
import pytest

from Pages.instance import InstancePage
from Pages.loginpage import LoginPage
from TestCases.conftest import setup_and_teardown
from selenium.webdriver import ActionChains
from Pages.Dashboardpage import Test_Login

@pytest.mark.usefixtures("setup_and_teardown")
class Test_Login_Dashboard_Page:
    def test_login_page_with_credentials(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        time.sleep(3)
        self.driver.quit()
    def test_dashboard_location(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        current_url = self.driver.current_url
        print(current_url)
        time.sleep(3)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "location.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()

    def test_dashboard_location_dropdown(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(3)
        login.location_dropdown()
        current_url = self.driver.current_url
        print(current_url)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "dropdown_location.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()
    # #
    def test_dashboard_total_instance(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(5)
        login.location_dropdown()
        login.dashboard_total_intances()
        login.dashboard_up_instances()
        login.dashword_down_instance()
        login.dashboard_instances()
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "dashboard_instance_total.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()

    def test_services(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(3)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login = Test_Login(self.driver)
        login.location()
        time.sleep(3)
        login.location_dropdown()
        login.service_total()
        login.service_ok()
        login.service_warn()
        login.service_crit()
        login.verify_total_service()
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "dashboard_service_total.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()

    def test_tickets(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login = Test_Login(self.driver)
        login.location()
        time.sleep(5)
        login.location_dropdown()
        login.tickets()
        login.pending_tickets()
        login.closed_tickets()
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "dashboard_total_tickets.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()


    def test_billing(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(5)
        login.location_dropdown()
        login.billing()
        billing_total = login.billing_total().text
        print(billing_total)

    def test_dashboard_instance_table_verify_instance_running_and_shutdown_state(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(5)
        login.location_dropdown()
        time.sleep(3)
        login.rows_per_page()
        time.sleep(2)
        login.rows_per_page_dropdown()
        login.verify_total_state()
        self.driver.quit()

    def test_dashboard_instance_table_state(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        login.rows_per_page()
        # time.sleep()
        login.rows_per_page_dropdown()
        # time.sleep(3)
        login.dashboard_instance_state_button()
        # time.sleep(2)
        # login.dashboard_table_state()
        self.driver.quit()
    #
    def test_dashboard_table(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login = Test_Login(self.driver)
        login.location()
        time.sleep(5)
        login.location_dropdown()
        time.sleep(5)
        login.rows_per_page()
        time.sleep(2)
        login.rows_per_page_dropdown()
        time.sleep(3)
        login.dashboard_total_rows()
        login.dashboard_total_columns()
        login.dashboard_table_data()
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "dashboard_table.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()


    def test_table_action_add_tag(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(2)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(4)
        login.dashboard_instance_table_action_button_for_add_tags()
        self.driver.quit()

    def test_table_action_edit_tag(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(2)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(4)
        login.dashboard_instance_table_action_button_for_edit_tags()
        self.driver.quit()

    def test_table_action_edit_instance(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(2)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(4)
        login.dashboard_instance_table_action_button_for_edit_instance()
        self.driver.quit()

    def test_table_action_performance(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(2)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(4)
        login.dashboard_instance_table_action_button_for_Performance()
        self.driver.quit()

    def test_table_action_assign_partner(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(2)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(4)
        login.dashboard_instance_table_action_button_for_Assign_Partner()
        self.driver.quit()

    def test_dashboard_instance_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(3)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(3)
        login.dashboard_instance()
        # time.sleep(2)
        # message = "Instances"
        # login.dashboard_verify_instance_page().__eq__(message)
        current_url = self.driver.current_url
        print(current_url)
        time.sleep(3)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "instance_page.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()

    def test_dashboard_backup_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(3)
        login.dashboard_backup()
        time.sleep(3)
        message = "JOBS HISTORY"
        assert login.dashboard_verify_backup_page().__eq__(message)
        current_url = self.driver.current_url
        print(current_url)
        time.sleep(3)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "backup_page.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()

    def test_dashboard_monitoring(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(5)
        login.location_dropdown()
        time.sleep(3)
        login.dashboard_monitoring_page()
        # message = "Services"
        # assert login.dashboard_monitoring_verify_page().__eq__(message)
        time.sleep(2)
        current_url = self.driver.current_url
        print(current_url)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "monitoring_page.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()


    def test_dashboard_Billing(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(2)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        login.dashboard_billing()
        time.sleep(3)
        message = "Total Balance | ₹0"
        assert login.dashboard_billing_verify_page().__eq__(message)
        time.sleep(2)
        current_url = self.driver.current_url
        print(current_url)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "billing_page.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()


    def test_dash_board_report_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(5)
        login.location_dropdown()
        time.sleep(3)
        login.report_page()
        # message = "Bandwidth"
        # assert login.verify_reports_page().__eq__(message)
        time.sleep(2)
        current_url = self.driver.current_url
        print(current_url)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "report_page.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()

    def test_dashboard_service_warn(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(2)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.Hover_over_dashboard()
        login.location_dropdown()
        login.dashboard_service_warn_button()
        time.sleep(2)
        login.service_warn_table_total_rows()
        time.sleep(2)
        login.service_warn_table_total_columns()
        time.sleep(2)
        login.service_warn_table_data()
        current_url = self.driver.current_url
        print(current_url)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "warn_report_table.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()



    def test_table_search(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(2)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        login.table_search_ipaddress()
        time.sleep(2)
        login.table_search_enter_ipaddress("10.187.1.42")
        time.sleep(3)
        current_url = self.driver.current_url
        print(current_url)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "table_search_ip_address.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()

    def test_table_csv_report(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(2)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        login.table_csv_report()
        time.sleep(3)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "dashboard_csv_report.png")
        self.driver.save_screenshot(screenshot_path)

    def test_table_pdf_report(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(5)
        login.location_dropdown()
        time.sleep(5)
        login.table_pdf()
        time.sleep(3)
        current_url = self.driver.current_url
        print(current_url)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "table_pdf_report.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()


    def test_dashboard_main_search(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(3)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.dashboard_main_search_button()
        login.search_ip_address("10.193.32.5")
        time.sleep(2)
        current_url = self.driver.current_url
        print(current_url)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "dashboard_main_search.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()


    def test_question_mark(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(3)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        # time.sleep(3)
        login.dashboard_question_mark()
        time.sleep(4)
        current_url = self.driver.current_url
        print(current_url)
        folder_path = "screenshots"
        screenshot_path = os.path.join(folder_path, "dashboard_question_mark_page.png")
        self.driver.save_screenshot(screenshot_path)
        self.driver.quit()

    def test_verify_dashboard_total_instance_page_total(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        login.service_total()
        time.sleep(2)
        instance = InstancePage(self.driver)
        time.sleep(3)
        instance.instance_page()
        time.sleep(3)
        instance.verify_total_service()
        self.driver.quit()

    def test_verify_dashboard_total_instance_page_ok(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        login.service_ok()
        time.sleep(2)
        instance = InstancePage(self.driver)
        time.sleep(3)
        instance.instance_page()
        time.sleep(3)
        instance.instance_table_ok_button()
        self.driver.quit()

    def test_verify_dashboard_total_instance_page_warn(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        login.service_warn()
        time.sleep(2)
        instance = InstancePage(self.driver)
        time.sleep(3)
        instance.instance_page()
        time.sleep(3)
        instance.instance_table_warn_button()
        self.driver.quit()

    def test_verify_dashboard_total_instance_page_crit(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        login = Test_Login(self.driver)
        login.Hover_over_dashboard()
        login.location()
        time.sleep(2)
        login.location_dropdown()
        time.sleep(2)
        login.service_crit()
        time.sleep(2)
        instance = InstancePage(self.driver)
        time.sleep(3)
        instance.instance_page()
        time.sleep(3)
        instance.instance_table_crit_button()
        self.driver.quit()




