import time
import pytest

from pages.dashboard import Test_Login
from pages.login_page import LoginPage
from pages.instance import InstancePage
from pages.ZoomViewPage import ZoomViewPage

@pytest.mark.usefixtures("setup_and_teardown")
class TestZoomView:
    # def test_login_page_with_credentials(self):
    #     login_page = LoginPage(self.driver)
    #     login_page.email_address("abdul@gmail.com")
    #     login_page.email_address_password("Tulasi@1234")
    #     login_page.click_login()
    #     time.sleep(5)
    #     self.driver.quit()
    def test_manage_zoomview_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_page()
        time.sleep(1)
        message = 'Zoom View'
        assert zoomview.verify_manage_page().__eq__(message)
        zoomview.current_url()
        # self.driver.save_screenshot("manage_zoomview_page.png")
        self.driver.quit()



    def test_verify_manage_zoomview_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        message = "Services"
        assert zoomview.verify_zoomview_page().__eq__(message)
        zoomview.current_url()
        # self.driver.save_screenshot("manage_verify_zoomview_page.png")
        self.driver.quit()

    def test_zoomview_service_page_select_one_instance(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.zoomview_service_button()
        time.sleep(1)
        zoomview.service_instance()
        time.sleep(1)
        zoomview.instance_data()
        time.sleep(2)
        zoomview.hostname_button()
        time.sleep(1)
        zoomview.hostname_data()
        time.sleep(2)
        # self.driver.save_screenshot("zoomview_page_select_one_instance_service.png")
        self.driver.quit()


    def test_zoomview_service_page_caputure_hostname_data(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.zoomview_service_button()
        time.sleep(1)
        zoomview.service_instance()
        time.sleep(1)
        zoomview.instance_data()
        time.sleep(2)
        zoomview.hostname_button()
        time.sleep(1)
        zoomview.hostname_data()
        time.sleep(2)
        # self.driver.save_screenshot("zoomview_page_select_one_instance_service.png")
        self.driver.quit()



    def test_service_table(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.service_button()
        time.sleep(1)
        zoomview.rows_drop_down_button()
        time.sleep(1)
        zoomview.rows_drop_down()
        time.sleep(1)
        zoomview.service_table_data()
        time.sleep(2)
        # self.driver.save_screenshot("zoomview_page_service_table_data.png")
        self.driver.quit()

    def test_service_total_instance_count(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(3)
        login.location_dropdown()
        zoomview = ZoomViewPage(self.driver)
        zoomview.dashboard_total_intances()
        # self.driver.save_screenshot("zoomview_page_total_service_panals.png")
        self.driver.quit()
        # zoomview.manage_zoomview_page()
        # time.sleep(1)
        # zoomview.service_button()
        # time.sleep(1)
        # zoomview.zoomview_service_button()
        # time.sleep(1)
        # zoomview.total_intsances()

    def test_pause_alerts_table(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(2)
        login.location_dropdown()
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.pause_alerts()
        time.sleep(1)
        zoomview.pause_alerts_table_data()
        time.sleep(1)
        # self.driver.save_screenshot("zoomview_page_total_service_pause_alrets_table.png")
        self.driver.quit()

    def test_zoomview_service_check_instance_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(3)
        login.location_dropdown()
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.zoomview_service_button()
        time.sleep(1)
        message = "Select Instance"
        assert zoomview.verify_instance_panel().__eq__(message)
        # self.driver.save_screenshot("zoomview_page_verify_service_instance_.png")
        self.driver.quit()

    def test_graph_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(1)
        login.location_dropdown()
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.select_graph()
        time.sleep(1)
        message = "15 mins data"
        assert zoomview.verify_graph_page().__eq__(message)
        # self.driver.save_screenshot("zoomview_page_verify_graph_page_.png")
        self.driver.quit()

    def test_graph_one_instance(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(1)
        login.location_dropdown()
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.select_graph()
        time.sleep(1)
        zoomview.graph_instance_button()
        time.sleep(1)
        zoomview.graph_select_instance_check_box()
        time.sleep(1)
        zoomview.graph_service_button()
        time.sleep(1)
        zoomview.graph_service_dropdown_list()
        time.sleep(1)
        zoomview.graph_interval_dropdown()
        time.sleep(1)
        zoomview.graph_dropdown_listitems()
        time.sleep(1)
        zoomview.graph_submit_button()
        self.driver.implicitly_wait(10)
        zoomview.verify_graph_instance()
        self.driver.quit()


    def test_graph_all_instance(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("zebu@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        login = Test_Login(self.driver)
        login.location()
        time.sleep(1)
        login.location_dropdown()
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.select_graph()
        time.sleep(1)
        zoomview.graph_instance_button()
        time.sleep(1)
        zoomview.graph_select_all_instance_check_box()
        time.sleep(1)
        zoomview.graph_service_button()
        time.sleep(1)
        zoomview.graph_service_dropdown_list()
        time.sleep(1)
        zoomview.graph_interval_dropdown()
        time.sleep(1)
        zoomview.graph_dropdown_listitems()
        time.sleep(1)
        zoomview.graph_submit_button()
        self.driver.implicitly_wait(10)
        zoomview.zoomview_graph_instances()
        time.sleep(2)
        zoomview.zoomview_instances_graph()
        self.driver.quit()

    def test_internet_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.internet_button()
        time.sleep(1)
        message = "Internet Activities"
        assert zoomview.verify_internet_activities_page().__eq__(message)
        # self.driver.save_screenshot("zoomview_page_verify_internet_page_.png")
        self.driver.quit()

    def test_internet_total_instances(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.internet_button()
        time.sleep(1)
        zoomview.internet_instance_button()
        time.sleep(1)
        zoomview.total_instances()
        time.sleep(1)
        # self.driver.save_screenshot("zoomview_page_internet_total_instances_.png")
        self.driver.quit()

    def test_internet_instance_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.internet_button()
        time.sleep(1)
        zoomview.internet_instance_button()
        time.sleep(1)
        zoomview.select_instances()
        time.sleep(3)
        zoomview.check_internet_interval_dropdown()
        time.sleep(1)
        zoomview.internet_dropdown_list()
        time.sleep(1)
        zoomview.internet_instance_submit()
        self.driver.implicitly_wait(10)
        zoomview.internet_hostname_arrow()
        time.sleep(1)
        zoomview.internet_hostname_data()
        time.sleep(1)
        # zoomview.internet_hostname_arrow()
        # time.sleep(1)
        zoomview.internet_instance_hostname()
        time.sleep(1)
        # self.driver.save_screenshot("zoomview_page_instance_page_.png")

        self.driver.quit()

    def test_internet_instance_page_check_interval(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.internet_button()
        time.sleep(1)
        zoomview.internet_instance_button()
        time.sleep(3)
        # message = "Select Instance"
        # assert zoomview.verify_internet_instance_text().__eq__(message)
        # time.sleep(2)
        zoomview.internet_interval_dropdown()
        time.sleep(1)
        zoomview.internet_dropdown_list()
        time.sleep(1)
        zoomview.verify_interval_button_text()
        time.sleep(1)
        # self.driver.save_screenshot("zoomview_page_verify_internet_instance_page_.png")
        self.driver.quit()



    def test_graph_instance_page_check_interval(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.select_graph()
        time.sleep(1)
        zoomview.internet_instance_button()
        time.sleep(1)
        # message = "Select Instance"
        # assert zoomview.verify_internet_instance_text().__eq__(message)
        # time.sleep(2)
        zoomview.graph_check_interval()
        time.sleep(1)
        zoomview.graph_dropdown_listitems()
        time.sleep(1)
        zoomview.verify_interval_button_text()
        time.sleep(1)
        # self.driver.save_screenshot("zoomview_page_verify_graph_instance_page_.png")
        self.driver.quit()

    def test_internet_activities_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.internet_button()
        self.driver.implicitly_wait(10)
        zoomview.internet_activities_page()
        time.sleep(1)
        zoomview.internet_activities_table()
        time.sleep(1)
        # self.driver.save_screenshot("zoomview_page_internet_activities_page_.png")
        self.driver.quit()

    def test_internet_external_communication_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(2)
        zoomview.internet_button()
        time.sleep(2)
        zoomview.internet_activities_page()
        time.sleep(1)
        zoomview.external_communication()
        time.sleep(1)
        zoomview.external_communication_table()
        time.sleep(1)
        zoomview.external_communication_table_data()
        time.sleep(2)
        self.driver.quit()

    def test_apps_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(4)
        zoomview.internet_button()
        time.sleep(4)
        zoomview.internet_activities_page()
        time.sleep(4)
        zoomview.apps()
        time.sleep(3)
        zoomview.apps_table()
        time.sleep(3)
        zoomview.apps_table_data()
        time.sleep(3)
        self.driver.quit()

    def test_city_wise_traffic_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        zoomview = ZoomViewPage(self.driver)
        time.sleep(3)
        zoomview.manage_zoomview_page()
        time.sleep(4)
        zoomview.internet_button()
        time.sleep(4)
        zoomview.internet_activities_page()
        time.sleep(4)
        zoomview.city_wise_traffic()
        time.sleep(3)
        zoomview.city_wise_traffic_table()
        time.sleep(4)
        zoomview.city_wise_traffic_table_data()
        time.sleep(3)
        self.driver.quit()

    def test_ISP_contributor_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        time.sleep(5)
        zoomview = ZoomViewPage(self.driver)
        time.sleep(3)
        zoomview.manage_zoomview_page()
        time.sleep(4)
        zoomview.internet_button()
        time.sleep(4)
        zoomview.internet_activities_page()
        time.sleep(4)
        zoomview.ISP_contributor()
        time.sleep(3)
        zoomview.ISP_contributor_table()
        time.sleep(3)
        zoomview.ISP_contributor_table_data()
        time.sleep(3)
        self.driver.quit()

    def test_session_flow_page(self):
        login_page = LoginPage(self.driver)
        login_page.email_address("abdul@gmail.com")
        login_page.email_address_password("Tulasi@1234")
        login_page.click_login()
        self.driver.implicitly_wait(10)
        zoomview = ZoomViewPage(self.driver)
        zoomview.manage_zoomview_page()
        time.sleep(1)
        zoomview.internet_button()
        time.sleep(1)
        zoomview.session_flow()
        time.sleep(1)
        zoomview.session_flow__table()
        time.sleep(3)
        zoomview.session_flow_table_data()
        # self.driver.save_screenshot("zoomview_page_internet_session_flow_page_.png")
        self.driver.quit()


