import time
import pytest
from pages.login_page import LoginPage
from pages.instance import InstancePage

@pytest.mark.usefixtures("setup_and_teardown")
class TestInstance:
     def test_login_page_with_credentials(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          instance.manage_page()
          time.sleep(1)
          message = "Instance"
          assert instance.verify_dashboard_manage_page().__eq__(message)
          instance.current_url()
          # self.driver.save_screenshot("manage_instance_page.png")
          self.driver.quit()

     def test_manage_instance_page(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          instance.location()
          time.sleep(1)
          instance.location_dropdown()
          time.sleep(1)
          instance.instance_page()
          time.sleep(1)
          message = "Instances"
          assert instance.verify_instances_text().__eq__(message)
          instance.current_url()
          # self.driver.save_screenshot("instance_page.png")
          self.driver.quit()

     def test_manage_instance_page_table_data(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          instance.location()
          time.sleep(1)
          instance.location_dropdown()
          time.sleep(2)
          instance.instance_page()
          time.sleep(1)
          instance.instance_page_table_data()
          # self.driver.save_screenshot("manage_instance_page_table.png")
          self.driver.quit()

     def test_manage_instance_table_click_on_instance(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          instance.location()
          time.sleep(2)
          instance.location_dropdown()
          time.sleep(2)
          instance.instance_page()
          time.sleep(2)
          instance.table_instance_button()
          time.sleep(2)
          instance.instance_page_under_table_data()
          # self.driver.save_screenshot("instance_page_table.png")

     def test_manage_instance_table_click_on_notification(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          instance.location()
          time.sleep(2)
          instance.location_dropdown()
          time.sleep(2)
          instance.instance_page()
          time.sleep(2)
          instance.table_instance_notification_button()
          time.sleep(2)
          instance.instance_page_under_notification_table_data()
          # self.driver.save_screenshot("instance_notification_data.png")
          self.driver.quit()


     def test_instance_performance(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          time.sleep(1)
          instance.location()
          time.sleep(1)
          instance.location_dropdown()
          time.sleep(1)
          instance.instance_page()
          time.sleep(1)
          instance.table_instance_action_performance()
          time.sleep(1)
          instance.action_performance()
          self.driver.implicitly_wait(10)
          mesage = ''
          instance.verify_performance_hostname_text()
          # instance.performance_instance_button()
          time.sleep(1)
          instance.zoomview_graphs_data()
          time.sleep(3)
          instance.graphs_data()
          time.sleep(1)
          instance.current_url()
          # self.driver.save_screenshot("instance_performance_page.png")


     def test_instance_performance_select_one_instance(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          time.sleep(1)
          instance.location()
          time.sleep(1)
          instance.location_dropdown()
          time.sleep(1)
          instance.instance_page()
          time.sleep(1)
          instance.table_instance_action_performance()
          time.sleep(1)
          instance.action_performance()
          self.driver.implicitly_wait(10)
          instance.verify_performance_hostname_text()
          time.sleep(1)
          instance.performance_instance_button()
          time.sleep(1)
          instance.select_one_instance_check_box()
          time.sleep(1)
          instance.service_button()
          time.sleep(1)
          instance.service_dropdown_list()
          time.sleep(1)
          instance.intervel_dropdown()
          time.sleep(2)
          instance.dropdown_listitems()
          time.sleep(2)
          instance.submit_button()
          self.driver.implicitly_wait(10)
          instance.instances_graph_text()
          # self.driver.save_screenshot("one_instance_performance_page.png")
          self.driver.quit()




     def test_instance_performance_select_all(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          time.sleep(1)
          instance.location()
          time.sleep(1)
          instance.location_dropdown()
          time.sleep(1)
          instance.instance_page()
          time.sleep(1)
          instance.table_instance_action_performance()
          time.sleep(1)
          instance.action_performance()
          self.driver.implicitly_wait(10)
          instance.performance_instance_button()
          time.sleep(1)
          instance.select_instance_check_box()
          time.sleep(1)
          instance.service_button()
          time.sleep(1)
          instance.service_dropdown_list()
          time.sleep(1)
          instance.intervel_dropdown()
          time.sleep(2)
          instance.dropdown_listitems()
          time.sleep(2)
          instance.submit_button()
          self.driver.implicitly_wait(20)
          instance.cpu_graph_instances()
          # self.driver.save_screenshot("instance_performance_page_data.png")

     def test_instance_warning(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          instance.location()
          time.sleep(1)
          instance.location_dropdown()
          time.sleep(1)
          instance.instance_page()
          time.sleep(1)
          instance.instance_warnings()
          time.sleep(1)
          instance.instance_page_warning_table_data()
          # self.driver.save_screenshot("instance_warnings.png")

     def test_instance_criticals(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(1)
          instance.instance_page()
          time.sleep(5)
          instance.instance_criticals()
          time.sleep(3)
          instance.critical_table_data()
          time.sleep(3)
          # self.driver.save_screenshot("instance_critical.png")

     def test_instance_table_ok(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          instance.location()
          time.sleep(1)
          instance.location_dropdown()
          # time.sleep(10)
          # instance.instance_page()
          time.sleep(1)
          instance.instance_table_ok_button()
          # self.driver.save_screenshot("instance_table_ok.png")

     def test_instance_table_warn(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(1)
          instance.instance_page()
          time.sleep(5)
          instance.instance_table_warn_button()
          # self.driver.save_screenshot("instance_table_warn.png")

     def test_instance_table_crit(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(1)
          instance.instance_page()
          time.sleep(5)
          instance.instance_table_crit_button()
          # self.driver.save_screenshot("instance_table_crit.png")


     def test_verify_instance_table_ok_and_dashboard_service_ok(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          time.sleep(1)
          instance.location()
          time.sleep(1)
          instance.location_dropdown()
          time.sleep(1)
          instance.verify_instance_table_ok_and_dashboard_ok()
          # instance.instance_page()
          # time.sleep(5)
          # instance.instance_table_ok_button()
          # self.driver.save_screenshot("instance_table_ok.png")



     def test_verify_instance_table_warn_and_ashboard_service_warn(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          time.sleep(1)
          instance.location()
          time.sleep(1)
          instance.location_dropdown()
          time.sleep(1)
          instance.verify_instance_table_warn_and_dashboard_warn()
          # self.driver.save_screenshot("instance_table_warn.png")


     def test_verify_instance_table_crit_and_ashboard_service_crit(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          time.sleep(1)
          instance.location()
          time.sleep(1)
          instance.location_dropdown()
          time.sleep(1)
          instance.verify_instance_table_crit_and_dashboard_crit()
          # self.driver.save_screenshot("instance_table_crit.png")


     def test_instance_table_verify_total(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          instance.location()
          time.sleep(2)
          instance.location_dropdown()
          time.sleep(2)
          # instance.instance_page()
          # time.sleep(5)
          instance.verify_total_service()
          # self.driver.save_screenshot("instance_table.png")


     def test_instance_table_warnings(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(3)
          instance.instance_warnings()
          time.sleep(3)
          instance.instance_no_of_warnings()
          # self.driver.save_screenshot("instance_table_warnings.png")

     def test_instance_table_criticals(self):
          login_page = LoginPage(self.driver)
          login_page.email_address("abdul@gmail.com")
          login_page.email_address_password("Tulasi@1234")
          login_page.click_login()
          self.driver.implicitly_wait(10)
          instance = InstancePage(self.driver)
          time.sleep(3)
          instance.location()
          time.sleep(3)
          instance.location_dropdown()
          time.sleep(10)
          instance.instance_page()
          time.sleep(3)
          instance.instance_criticals()
          time.sleep(3)
          instance.instance_no_of_criticals()
          # self.driver.save_screenshot("instance_table_criticals.png")





































# import time
# import pytest
# from Pages.loginpage import LoginPage
# from Pages.instance import InstancePage
#
# @pytest.mark.usefixtures("setup_and_teardown")
# class TestInstance:
#      def test_login_page_with_credentials(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           self.driver.quit()
#
#      def test_manage_instance_page(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           message = "Instances"
#           assert instance.verify_instances_text().__eq__(message)
#           time.sleep(3)
#           self.driver.quit()
#      def test_manage_instance_page_table(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           time.sleep(3)
#           instance.instance_total_rows()
#           time.sleep(3)
#           instance.instance_total_columns()
#           time.sleep(3)
#           instance.instance_table_data()
#           self.driver.quit()
#
#      def test_manage_instance_table_click_on_instance(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(5)
#           instance.instance_page()
#           time.sleep(4)
#           instance.table_instance_button()
#           time.sleep(5)
#           instance.table_instance_data()
#
#      def test_manage_instance_table_click_on_notification(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(5)
#           instance.instance_page()
#           time.sleep(4)
#           instance.table_instance_notification_button()
#           time.sleep(4)
#           instance.table_instance_notification_data()
#           self.driver.quit()
#
#
#      def test_instance_performance(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           time.sleep(3)
#           instance.table_instance_action_performance()
#           time.sleep(3)
#           instance.action_performance()
#           time.sleep(3)
#           instance.performance_instance_button()
#
#      def test_instance_performance_select(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           time.sleep(3)
#           instance.table_instance_action_performance()
#           time.sleep(3)
#           instance.action_performance()
#           time.sleep(5)
#           instance.performance_instance_button()
#           time.sleep(5)
#           instance.select_instance_check_box()
#           time.sleep(5)
#           instance.service_button()
#           time.sleep(5)
#           instance.service_dropdown_list()
#           time.sleep(5)
#           instance.intervel_dropdown()
#           time.sleep(10)
#           instance.dropdown_listitems()
#           time.sleep(5)
#           instance.submit_button()
#           time.sleep(3)
#
#      def test_instance_warning(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           time.sleep(3)
#           instance.instance_warnings()
#           time.sleep(3)
#           instance.warning_table_data()
#
#      def test_instance_criticals(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           time.sleep(5)
#           instance.instance_criticals()
#           time.sleep(3)
#           instance.critical_table_data()
#           time.sleep(3)
#
#      def test_instance_table_ok(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           time.sleep(5)
#           instance.instance_table_ok_button()
#
#      def test_instance_table_warn(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           time.sleep(5)
#           instance.instance_table_warn_button()
#
#      def test_instance_table_crit(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           time.sleep(5)
#           instance.instance_table_crit_button()
#
#
#      def test_instance_table_verify_total(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           time.sleep(5)
#           instance.verify_total_service()
#
#
#      def test_instance_table_warnings(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           time.sleep(3)
#           instance.instance_warnings()
#           time.sleep(3)
#           instance.instance_no_of_warnings()
#
#      def test_instance_table_criticals(self):
#           login_page = LoginPage(self.driver)
#           login_page.email_address("abdul@gmail.com")
#           login_page.email_address_password("Tulasi@1234")
#           login_page.click_login()
#           time.sleep(5)
#           instance = InstancePage(self.driver)
#           time.sleep(3)
#           instance.location()
#           time.sleep(3)
#           instance.location_dropdown()
#           time.sleep(10)
#           instance.instance_page()
#           time.sleep(3)
#           instance.instance_criticals()
#           time.sleep(3)
#           instance.instance_no_of_criticals()
#
#
#
#
